---
title: "Reduced Genes"
author: "Edie Espejo"
output: html_document
---

```{r}
library(readr)
endo <- read_csv("../../data/machine-learning/two-fold/model-8020.csv")[,-1]
names(endo)[1] <- "id"
head(endo)
```

```{r}
library(dplyr)
gene_predictors <- endo %>% dplyr::select(-id, -tissue, -endometriosis, -severity)
outcome         <- ifelse(endo %>% dplyr::select(endometriosis)=="Endometriosis", 1, 0)
```

# Removal of highly correlated variables

https://stackoverflow.com/questions/18275639/remove-highly-correlated-variables
```{r}
library(caret)
df2 <- cor(gene_predictors)
hc  <- findCorrelation(df2, cutoff=0.7) # putt any value as a "cutoff" 
hc  <- sort(hc)
reduced_genes <- gene_predictors[,-c(hc)]
dim(reduced_genes)
```




# SuperLearner

https://cran.r-project.org/web/packages/SuperLearner/vignettes/Guide-to-SuperLearner.html


## Fitting the SuperLearner Models

```{r}
# install.packages("LogicReg")
library(SuperLearner)
# listWrappers()
# * GLMNET IS LASSO
sl_lib <- c("SL.mean", "SL.knn", "SL.svm", "SL.glmnet", "SL.randomForest", "SL.lda",  "SL.nnet", "SL.bayesglm")
```

### NNLS Loss

```{r}
sl_fit_nnls <- SuperLearner(Y=outcome, X=reduced_genes, family=binomial(), SL.library=sl_lib)
sl_fit_nnls
```


### AUC Loss

```{r}
sl_lib_auc <- c("SL.mean", "SL.svm", "SL.glmnet", "SL.randomForest", "SL.lda",  "SL.nnet", "SL.bayesglm")
sl_fit_auc <- SuperLearner(Y=outcome, X=reduced_genes, family=binomial(), SL.library=sl_lib_auc, method = "method.AUC")
sl_fit_auc
```



### NN log likelihood Loss

```{r}
sl_fit_ll <- SuperLearner(Y=outcome, X=reduced_genes, family=binomial(), SL.library=sl_lib, method = "method.NNloglik")
sl_fit_ll
```


# Prediction

```{r}
endo_2 <- read_csv("../../data/machine-learning/two-fold/validation-8020.csv")[,-1]
names(endo_2)[1] <- "id"
gene_predictors_2 <- endo_2 %>% dplyr::select(-id, -tissue, -endometriosis, -severity) %>% dplyr::select(names(reduced_genes)) 
outcome_2         <- ifelse(endo_2 %>% dplyr::select(endometriosis)=="Endometriosis", 1, 0)
```


### NNLS Loss


```{r}
pred_nnls    <- predict(sl_fit_nnls, gene_predictors_2, onlySL=T)
pred_nnls_df <- data.frame(cbind(round(pred_nnls$pred), outcome_2))
sum(pred_nnls_df[,1]==pred_nnls_df[,2]) / nrow(pred_nnls_df)
```

### AUC Loss

```{r}
pred_auc    <- predict(sl_fit_auc, newdata=gene_predictors_2)
pred_auc_df <- data.frame(cbind(round(pred_auc$pred), outcome_2))
sum(pred_auc_df[,1]==pred_auc_df[,2]) / nrow(pred_auc_df)
```

### NN log-likelihood Loss


```{r}
pred_ll    <- predict(sl_fit_ll, gene_predictors_2, onlySL=T)
pred_ll_df <- data.frame(cbind(round(pred_ll$pred), outcome_2))
sum(pred_ll_df[,1]==pred_ll_df[,2]) / nrow(pred_ll_df)
```



# ROC
https://cran.r-project.org/web/packages/plotROC/vignettes/examples.html
```{r}
library(ROCR)
pred_auc_rocr <- prediction(predictions=pred_auc$pred, labels=outcome_2)
perf_auc_rocr <- performance(pred_auc_rocr,"tpr","fpr")

plot_auc <- function(performance_s4_obj, title="") {
  require(ggplot2)
  perf_auc_rocr_df <- data.frame(cbind(x=unlist(performance_s4_obj@x.values),
                                       y=unlist(performance_s4_obj@y.values)))
  ggplot2::ggplot(perf_auc_rocr_df, aes(x=x, y=y)) + 
    geom_point() + 
    geom_line() + 
    xlab("Specificity") + 
    ylab("Sensitivity") +
    ggtitle(title)
}

plot_auc(perf_auc_rocr, title="ROC under SuperLearner AUC Loss")
```

```{r}
pred_nnls_rocr <- prediction(predictions=pred_nnls$pred, labels=outcome_2)
perf_nnls_rocr <- performance(pred_nnls_rocr,"tpr","fpr")
plot_auc(perf_nnls_rocr, title="ROC under SuperLearner NNLS Loss")
```

```{r}
pred_ll_rocr <- prediction(predictions=pred_ll$pred, labels=outcome_2)
perf_ll_rocr <- performance(pred_ll_rocr,"tpr","fpr")
plot_auc(perf_ll_rocr, title="ROC under SuperLearner NNLL Loss")
```

