---
title: "Getting machine learning data ready"
author: "Edie Espejo"
date: "12/3/2018"
output: html_document
---

# Two-Fold Method

```{r}
full_data <- read.csv("../../data/genbank/06-twofold-genes.csv-data.csv", as.is=TRUE, stringsAsFactors=FALSE)[,-1]
head(full_data)
```

```{r}
test_n  <- round(nrow(full_data)*0.1)
train_n <- nrow(full_data) - round(nrow(full_data)*0.1)

c(test_n, train_n)
```


```{r}
random_ix <- sample(x=c(1:148), test_n)
random_ix
```

```{r}
final_validation <- full_data[random_ix,]
write.csv(final_validation, "../../data/machine-learning/final_validation.csv")
```

```{r}
random_ix_leftover <- setdiff(c(1:148), random_ix)
model_building     <- full_data[random_ix_leftover,]
write.csv(model_building, "../../data/machine-learning/model_building.csv")
```

# Mann-Whitney Method

### 80-20 
```{r}
full_data <- read.csv("../../data/genbank/06-mw-genes.csv", as.is=TRUE, stringsAsFactors=FALSE)[,-1]
head(full_data)
```

```{r}
test_n  <- round(nrow(full_data)*0.2)
train_n <- nrow(full_data) - round(nrow(full_data)*0.2)

c(test_n, train_n)
```


```{r}
random_ix <- sample(x=c(1:148), test_n)
random_ix
```

```{r}
final_validation <- full_data[random_ix,]
write.csv(final_validation, "../../data/machine-learning/mann-whitney/validation-8020.csv")
```

```{r}
random_ix_leftover <- setdiff(c(1:148), random_ix)
model_building     <- full_data[random_ix_leftover,]
write.csv(model_building, "../../data/machine-learning/mann-whitney/model-8020")
```


### 90-10 
```{r}
full_data <- read.csv("../../data/genbank/06-mw-genes.csv", as.is=TRUE, stringsAsFactors=FALSE)[,-1]
head(full_data)
```

```{r}
test_n  <- round(nrow(full_data)*0.1)
train_n <- nrow(full_data) - round(nrow(full_data)*0.1)

c(test_n, train_n)
```


```{r}
random_ix <- sample(x=c(1:148), test_n)
random_ix
```

```{r}
final_validation <- full_data[random_ix,]
write.csv(final_validation, "../../data/machine-learning/mann-whitney/validation-9010.csv")
```

```{r}
random_ix_leftover <- setdiff(c(1:148), random_ix)
model_building     <- full_data[random_ix_leftover,]
write.csv(model_building, "../../data/machine-learning/mann-whitney/model-9010")
```